let MenuList = [
  {
    name:"ハンバーグステーキ",
    price:400,
    category:"main"
  }
  ,
  {
    name:"ミラノ風ドリア",
    price:300,
    category:"main"
  }
  ,
  {
    name:"小エビのサラダ",
    price:350,
    category:"salad"
  }
  ,
  {
    name:"辛味チキン",
    price:300,
    category:"sub"
  }
  ,
  {
    name:"ポップコーンシュリンプ",
    price:300,
    category:"sub"
  }
  ,
  {
    name:"ティラミス クラシコ",
    price:300,
    category:"dessert"
  }
  ,
  {
    name:"小エビのカクテル",
    price:280,
    category:"salad"
  }
  ,
  {
    name:"エスカルゴのオーブン焼き",
    price:400,
    category:"sub"
  }
  ,
  {
    name:"チョリソー",
    price:400,
    category:"sub"
  }
  ,
  {
    name:"ほうれん草のソテー",
    price:200,
    category:"salad"
  }
  ,
  {
    name:"柔らか青豆の温サラダ",
    price:200,
    category:"salad"
  }
  ,
  {
    name:"チキンのサラダ",
    price:350,
    category:"salad"
  }
  ,
  {
    name:"たまねぎのズッパ",
    price:300,
    category:"sub"
  }
  ,
  {
    name:"田舎風ミネストローネ",
    price:300,
    category:"sub"
  }
  ,
  {
    name:"バッファローモッツアレラのマルゲリータピザ",
    price:400,
    category:"pizza"
  }
  ,
  {
    name:"たっぷりコーンのピザ",
    price:400,
    category:"pizza"
  }
  ,
  {
    name:"ソーセージピザ",
    price:400,
    category:"pizza"
  }
  ,
  {
    name:"野菜ときのこのピザ",
    price:400,
    category:"pizza"
  }
  ,
  {
    name:"半熟卵のミラノ風ドリア",
    price:350,
    category:"main"
  }
  ,
  {
    name:"ミラノ風ドリア+フォッカチオ",
    price:450,
    category:"main"
  }
  ,
  {
    name:"半熟卵のミラノ風ドリア+フォッカチオ",
    price:500,
    category:"main"
  }
  ,
  {
    name:"タラコとポップコーンシュリンプのドリア",
    price:400,
    category:"main"
  }
  ,
  {
    name:"タラコソースシシリー風",
    price:400,
    category:"main"
  }
  ,
  {
    name:"カルボナーラ",
    price:500,
    category:"main"
  }
  ,
  {
    name:"小エビのタラコソース",
    price:540,
    category:"main"
  }
  ,
  {
    name:"パルマ風スパゲッティ",
    price:400,
    category:"main"
  }
  ,
  {
    name:"きのことほうれん草のクリームスパゲッティ",
    price:600,
    category:"main"
  }
  ,
  {
    name:"イカの墨入りセビアソース",
    price:500,
    category:"main"
  }
  ,
  {
    name:"ミートソースボロニア風",
    price:400,
    category:"main"
  }
  ,
  {
    name:"ペペロンチーノ",
    price:300,
    category:"main"
  }
  ,
  {
    name:"スープ入り塩味ボンゴレ",
    price:500,
    category:"main"
  }
  ,
  {
    name:"ミックスグリル",
    price:650,
    category:"main"
  }
  ,
  {
    name:"イタリアンハンバーグ",
    price:500,
    category:"main"
  }
  ,
  {
    name:"ディアボラ風ハンバーグ",
    price:500,
    category:"main"
  }
  ,
  {
    name:"若鶏のディアボラ風",
    price:500,
    category:"main"
  }
  ,
  {
    name:"イタリアンプリン",
    price:250,
    category:"dessert"
  }
  ,
  {
    name:"プリンとティラミス　クラシコの盛り合わせ",
    price:500,
    category:"dessert"
  }
  ,
  {
    name:"ミルクジェラート",
    price:250,
    category:"dessert"
  }
  ,
  {
    name:"チョコレートケーキ",
    price:300,
    category:"dessert"
  }
  ,
  {
    name:"トリフアイスクリーム",
    price:350,
    category:"dessert"
  }
  ,
  {
    name:"コーヒーゼリー＆ミルクジェラート",
    price:350,
    category:"dessert"
  }
  ,
  {
    name:"セットドリンクバー",
    price:200,
    category:"additional"
  }
  ,
  {
    name:"コーンクリームスープ",
    price:150,
    category:"additional"
  }
  ,
  {
    name:"グラスワイン白",
    price:100,
    category:"wine"
  }
  ,
  {
    name:"グラスワイン赤",
    price:100,
    category:"wine"
  }
  ,
  {
    name:"ハンバーグステーキ+ライス",
    price:550,
    category:"main"
  }
];

const RandomButton = document.getElementById("button");
const result = document.getElementById("result");
RandomButton.addEventListener("click", function() {
  let MenuLists = [...MenuList];
  let sumPrice= 1000;
  let resultMenu = [];
  let endCount = 0;
  while(sumPrice>0){
    let randomIndex = Math.floor(Math.random() * MenuLists.length);
    let RandomMenu = MenuLists[randomIndex];
    if(RandomMenu.price <= sumPrice){
      resultMenu.push(RandomMenu);
      sumPrice = sumPrice - (RandomMenu.price);
      MenuLists = MenuLists.filter(menu => menu.category !== RandomMenu.category);
      endCount=0;
    }else{
      endCount++;
    }
    if(endCount==MenuLists.length){
      break;
    }
  }
  let text = "";
  for(let i=0; i<resultMenu.length; i++){
    text += resultMenu[i].name + "　価格："+ (resultMenu[i].price+"円\n");
  }
  result.textContent = text;
});
